FROM python:3-buster
EXPOSE 80

ENV RUNTIME_USER=runtime-user
ENV LED_BOX_DIR=/opt/led-box
ENV API_SERVER_DIR=${LED_BOX_DIR}/led-box-api-server

RUN apt-get update
RUN apt-get install git nginx gettext -y
RUN pip install uwsgi flask

#NGINX CONFIG
COPY nginx-config /etc/nginx/sites-available/led-box
RUN envsubst < /etc/nginx/sites-available/led-box > /etc/nginx/sites-available/led-box.tmp 
RUN mv /etc/nginx/sites-available/led-box.tmp /etc/nginx/sites-available/led-box
RUN ln -s /etc/nginx/sites-available/led-box /etc/nginx/sites-enabled

#CLONE
RUN mkdir -p ${LED_BOX_DIR}
RUN git clone https://github.com/thewiso/led-box.git ${LED_BOX_DIR}
WORKDIR ${API_SERVER_DIR}
RUN pip install -r requirements.txt
RUN cp ${LED_BOX_DIR}/docker/start-components.sh start-components.sh

#USER
RUN adduser ${RUNTIME_USER} --ingroup www-data --disabled-password --gecos ""
RUN chown -R ${RUNTIME_USER} ${API_SERVER_DIR}
RUN chmod u+x start-components.sh

CMD ./start-components.sh